name: Deployer CI
on:
  push:
    branches:
      - main
  pull_request_review:
    branches:
      - main  
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * 1"

jobs:
  TEST:
    name: Deployer Testing
    runs-on: ubuntu-latest
    steps:
      - name: Test Creation of files
        uses: actions/checkout@v2
        with:
          path: .
          message: "Test creation of files"
      - name: Test Application
        run: |
          mkdir -p /tmp/test
          ls -a
          cp . -r /tmp/test
          cd /tmp/test
          ./init.sh
          cat test.json
          rm -rf /tmp/test
          echo completed the test

      
